import React from 'react'
import styled from 'styled-components'

const ChNum = styled.h1`
  font-size: 2rem;
`

const ChTit = styled.h2`
  font-size: 1.5rem;
`

const ChBod = styled.div`
  width: 900px;
  max-width: 90%;
  margin: 1rem auto;
  p:first-of-type:first-line {
    // text-transform: uppercase;
  }
`

export default () => (
  <div>
    <header>
      <h1 className="title">THE OPENING DOOR</h1>
      <h2 className="byline">By <span className="author">Helen Reilly</span></h2>
      <p className="teaser">This is the story of a beautiful and haunted young woman.<br /><br /><em>When she was one year old, she was worth nine hundred thousand dollars.<br /><br />At twenty-one, she was sole heir to five million.<br /><br />Before she was twenty-two, she had endured more heartache, greed and violence than her whole estate was worth.</em><br /><br />It was anyone's guess whether she would ever see twenty-three.</p>
      <hr />
    </header>
    <main>
      <section style={{ width: '800px', border: '1px solid black', margin: '0 auto', padding: '1rem'}}>
        <ChNum>CHAPTER 1</ChNum>
        <ChTit>The Return of The Prodigal</ChTit>
        <ChBod>
          <p>The murder didn’t take place until after 7 p.m. on the night of December 2nd. At twenty minutes past four on the afternoon of that day, Eve Flavell reached the house that had once been her home on Henderson Square. She looked at her watch as she went around the corner. It had turned cold in mid-morning and fog had come sweeping in from the sea. The Square was full of it. The tops of the trees in the private park about which the Square was built stood up out of the fog faintly golden or black-branched against grayness; the leaves still clung tenaciously to the oaks and beeches. Lighted windows had begun to surround the Square on all four sides like colored lanterns hemming in a lovely wood.</p>
          <p>Most of the children in the park had gone home. Those that were still there behind the high iron fence and the concealing shrubbery weren’t making any noise. A sparrow chattered and a taxi honked. The wind was bleak. Eve Flavell shivered and flattened her shoulders under the raspberry tweed of her coat. Almost there now, she thought. How long was it since the last time — two months, three? She couldn’t remember.</p>
          <p>She paused opposite the house she had come to visit, the house in which she had lived for a good many years. It was her half-sister Natalie’s. The family had come here from the country when Nat was five, so that she could go to Miss Grant’s kindergarten on Henderson Place, where her mother, long since dead, had gone as a child. It was a beautiful house, of warm red brick with blue shutters and a white fan-light door. It had a groomed, cared-for, a washed and brushed and combed look, was prosperous, graceful, benign. It stood on the west side of the Square between two less ornamental neighbors and the anonymous and soaring bulk of an apartment hotel.</p>
          <p>Eve stared at the brass knocker glimmering through the dusk. In a moment she would cross the street, mount the steps and use the knocker. It would rap with a brisk thud, the door would open and that would be the end — of one part of her existence, at least, a part for which she had fought hard and that she hated to relinquish. She put out a narrow arched foot in a red calf sandal, drew it back and remained on the curb, asking herself for the twentieth time in the space of an hour whether it wouldn’t have been just as well to phone. The news would be the same over the wire as if she delivered it in person. She told herself angrily that she was being a fool. What difference did it make how the thing was done as long as it was finally accomplished? Sooner or later she would have to meet them all face to face, and there were generally people to tea and it would be easier in a crowd. Or would it? The matter was taken suddenly out of her hands.</p>
          <p>**</p>
          <p>"Eve, hello."</p>
          <p>A woman was calling to her from inside the park. Eve turned. It was Alicia, her brother Gerald's wife. She was coming down the path between bushes beaded with moisture. Alicia walked stiltedly on high heels, her hips swaying. Eve wondered how long she had been there, whether she had been watching her own imbecile indecision. Alicia's eyes were bright and inquisitive as she opened the tall iron gate, let it fall to behind her with a clang and joined Eve on the pavement. She began to talk in her soft, clear, mannered voice when she was ten feet away.</p>
          <p>"Eve, dear, this is wonderful. It's ages since we've met, centuries, practically. Why didn't you come to my Thanksgiving party? I was sorry I was out when you called or I wouldn't have taken any excuse. Work's all very well but you can run it into the ground. What a perfectly stunning hat, my dear &mdash; but then you always look marvelous."</p>
          <p>Eve knew she looked nothing of the kind. You couldn't fight your way through a mental knothole for forty-eight hours and come out on the other side unscathed. She was unpleasantly conscious of her pallor, her burning lids, although she had done what she could with pancake, lipstick and rouge.</p>
          <p>Alicia was examining her with large brown eyes that appeared to operate on ball bearings. They were slightly protuberant and exceedingly acute. Eve was afraid of them. She asked hurriedly after her brother, her five-year-old nephew. "How is Gerald, Alicia? How's Bunny?"</p>
          <p>Gerald and Bunny were fine, simply fine. Gerald was worried about business. The investment market was shot. But definitely. And nurses &mdash; Alicia threw up her hands &mdash; they were practically impossible to get. She'd had three in as many weeks; she'd just been in the park checking up on the latest gem, a woman with no teeth and a jaw that ought to be tied up in a rag. She said with a thin ribbon of bitterness under her vivacity, "It's funny, isn't it, Natalie's grown richer and richer and we're getting poorer and poorer? Well, that's the way it goes."</p>
          <p>Her meaningless laugh grated against Eve's ears. The silver fox jacket Alicia had on was a present from Natalie and probably the hand-sewn shoes and the alligator Bag. Eve said flatly, "Natalie can't help it if her money's invested in a factory that turns out what's in demand, can she?"</p>
          <p>Alicia gave a cry. She looked resentful, hurt. "Of course not, don't be silly, Eve. That's not what I meant at all. You do manage to twist things. Are you coming or going?"</p>
          <p>"I'm on my way in."</p>
          <p>The two women crossed the street together and mounted the steps. Eve thought, <em>It's coming closer</em>. Alicia kept on talking. "Aunt Charlotte's back, you know. Her stay on the farm doesn't seem to have done her the slightest bit of good. She looks worse than when she went up to Vermont in July. She looks frightful, really. Wait until you see her."</p>
          <p>Eve said quietly, "I have seen her. She stopped in at the shop the day before yesterday."</p>
          <p>Alicia showed her surprise. "Then you've made it up. Oh, my dear, I'm so pleased. Feuding's silly." Her tone was cordial, her eyes were probing. "She isn't looking well, is she? I was horrified when I first saw her. Of course she isn't getting any younger.  &hellip;  So you're friends again."</p>
          <p>Eve and Charlotte Foy, the aunt who had brought up the three of them &mdash; her brother and Natalie and herself &mdash; could never be friends. They were as far apart as the poles, had absolutely nothing in common, except a vast mutual distaste and their mutual love for Natalie. Her aunt had disliked and distrusted Eve since she was a child. It was to prove Charlotte wrong, to keep her from hurting Natalie, that Eve was there. She wasn't going to tell Alicia that. She said aloud, smiling lightly, "We were never anything but friends, underneath. It was simply that we didn't understand each other. But one grows older and wiser &mdash; we'll hope."</p>
          <p>The door was opening. Eve tried to relax tight muscles and followed her sister-in-law over the threshold. The staircase rose gracefully at the right and swung up across the rear wall. A great clump of rust-colored chrysanthemums bloomed on the Pembroke table beneath an old mirror that reflected the exquisite lines of the red chalk drawing Cheverin had done of Natalie's mother as a bride. The clock ticked on the landing; it was around Eve again, untouched, unchangeable, the atmosphere from which she had fled, orderly and gracious and serene and, to her, at least, completely poisonous. It pressed up against her stiflingly. Almost, then, she made a movement of retreat. It was too late. The maid closed the front door behind them, shutting out the fog and the cold December air. As she did so, Eve's young half-sister, Natalie, came through an archway on the left.</p>
          <p>Natalie wasn't pretty but she was ineffably smart. She was tall for a girl, five feet six, with a narrow, fine-featured face set in a frame of hair the color of unbeaten flax. It was cut in a long bob that swept her shoulders. Her eyes, big and brown and shining under a convex forehead, gave her the air of a serious child. Everything about her was long and narrow, her straight nose, her wide delicate-lipped mouth, her arms and legs and hands and feet. Blue veins showed in her slender wrists below the bracelet sleeves of a brown wool dirndl with a, swinging skirt. She wasn't really frail, but Charlotte had fussed over her health from babyhood. In Eve's opinion, if her young half-sister had been flung out into the Maine woods with a rusty tin cup to forage for herself, she would soon have put on the weight her bones called for. Her expression was aloof and a little haughty. It changed to one of quick pleasure when she saw Eve.</p>
          <p>"Darling &mdash; I didn't know you were coming," she exclaimed. "I expected Alicia but not you. I'm so glad.  &hellip;  How did you manage to get away? Never mind &mdash; you're here now anyhow. Come on in to the fire." She linked an arm through Eve's with one of her quick impetuous movements. "There are some people, but they'll go soon and we can talk. I was going to call you. I was thinking we might all go up to the country for a weekend when Bruce gets back. He's in Washington, you know."</p>
          <p>Bruce Cunningham, to whom Natalie was engaged, was a lieutenant in the Air Force. Injured in maneuvers, he was on leave of absence.</p>
          <p>Eve said she couldn't stay long. She noticed with a flicker of uneasiness that Natalie looked tired, that she was thinner, more vibrant, that her laugh was too brittle, her voice too gay. Her very white skin, skin that went naturally with her fair hair, had a faintly sallow tinge, and the spatter of freckles across the bridge of her straight nose was in evidence &mdash; always a sign that she wasn't her usual self. When she was little, when she was growing up, it was the first thing that people &mdash; nurses, governesses and tutors, Charlotte &mdash; always said: <em>You're freckles are showing, Nat.</em></p>
          <p>Alicia said it now. She was extremely observant. "Freckles, Nat, darling &hellip; . What's the matter? Have you been overdoing it with your countless social aid things? You'll wear yourself out. You shouldn't &mdash; "</p>
          <p>Natalie said with a touch of impatience &mdash; she could be imperious when she wanted to &mdash; "I'm all right. I wish you wouldn't, Alicia. I mean &mdash; don't say anything in front of Charlotte, for heaven's sake. She worries so &mdash; and she's not well."</p>
          <p>The three women entered the big sunken living-room, to the left of the hall and down a shallow flight of steps. The sea-green draperies at the windows were drawn. Lamplight drew gleams from the fine pieces of old furniture rubbed to a mirror-like smoothness, shone tranquilly on low bookcases, gaily colored satin chairs, and a few good pictures punctuating the ivory wall. Natalie had done the room over in April, on her twenty-first birthday. It was a decided improvement. Men and women stood or sat about in groups, talking in the muted well-bred way in which the Flavell parties were always conducted. Alicia darted off to join friends, and Eve nodded to several people she knew distantly and followed Natalie to the fire.</p>
          <p>Sofas flanked the white mantel under which flames leaped cheerfully. Eve's father Hugh Flavell and her aunt, Charlotte Foy, were on one of the sofas; Charlotte sat upright behind the tea things, her capable hands busy. Hugh lounged beside her, tall and thin, with his slight scholar's stoop, his eyes palely blue behind pince-nez, his receding hair brushed smoothly back from the high forehead of his handsome aquiline face. His serenity, his savoir-faire, his air of being able to command any situation under the sun were contradicted and betrayed by a small neat mouth under a clipped mustache that pouted in repose and was stubborn.</p>
          <p>He looked younger and more alive than Eve could recall. Charlotte, on the contrary, looked older and stonier, yet there was very little difference between their ages; Hugh was fifty-one and Charlotte fifty-four.</p>
          <p>"Dad, Charlotte &mdash; look who's here," Natalie said gaily. "She came of her own accord, I swear it."</p>
          <p>If Eve's unsolicited presence in the house from which she had voluntarily and drastically separated herself a long while ago caused either her father or her aunt any surprise, there was no evidence of it except, perhaps, in an overlong glance from Charlotte.</p>
          <p>Hugh said, "Ah, Eve, my dear. How are you? You're looking well." There was courtesy but no pleasure in his greeting. Eve didn't expect it. Her father and she had never been close, and after some of the things she had said in her young violence, four years earlier, they probably never would be. Hugh was not a forgiving person. She could hardly blame him. Charlotte produced words as though she were measuring spoonfuls of sugar. She now said in her measured tones, "Nice to see you here, Eve. Sit down. Tea? No? You'll probably want a drink."</p>
          <p>Eve had wanted tea. She settled herself in the corner of the opposite sofa and smiled at her aunt. "A drink, please, Charlotte &mdash; but I do wish you'd get over the horrid habit of being right. You know me too well &mdash; and all my sins."</p>
          <p>The moment the remark was out she regretted it. Charlotte flushed and drew in her breath, and Hugh's brows rose humorously. Natalie, who had turned aside to beckon to one of the maids, looked distressed. Eve knew she was being a fool, but for the life of her she couldn't help it. The very sight of Charlotte rubbed her the wrong way. It always had. She was so correct, so wrapped in rectitude; if only she wouldn't thrust it down your throat, Eve thought, and reminded herself that she hadn't come to quarrel; she had come for another and very definite purpose. Once it was accomplished she could go and not return.</p>
          <p>Nevertheless, sitting there in the familiar room, a sudden childish lump rose in her throat and for a moment she found herself wishing that she had had a more normal youth, that her mother, had lived, that her father hadn't married again, into money, even that her stepmother hadn't died &mdash; in which case Charlotte would never have appeared on the scene. She and Eve's own mother had been sisters, but the love Charlotte had for Gerald, Eve's brother, had skipped Eve and had fastened on Natalie, Hugh's daughter by his second wife.</p>
          <p><em>Stop being maudlin, you're accumulating a genuine complex</em>, she told herself. Charlotte was a good woman, as honest as the day, just, never deliberately unkind and about as imaginative as a flagpole. It wasn't her fault. It was the way she was made. Her position as the keeper of the keys, the manager of the household she ran on velvet had added to a bump of authority already too well developed. It was a pity she had never married. She was still good-looking, her black dress was smart, her iron-gray hair becomingly arranged. She turned to speak to a guest, and a start went through Eve. Alicia and Nat were right. There was something wrong with Charlotte, something terribly wrong. Firelight flared. In its momentary brilliance she looked frightful. Her skin was a bad color and she obviously wasn't well, but it wasn't only that. There was a queer fixity to her, as though within the ramparts of her substantial body her spirit had crumpled and was dead, or dying.</p>
          <p>Eve felt it then for the first time but not for the last time while she was in the room, the house, on that December afternoon: a sense of strangeness, of something wrong, twisted, that had no connection with her own private problem. The tension was in her father and Natalie as well as in her aunt. She tried to track it to its source and failed. But it was there, oh, very distinctly, in Hugh's absent pleasantries to his guests, in the tightness of his mouth, in the restless straying of his shapely hands. It was in Natalie, behind surface brightness, in her dutiful circling around the room, her fair head shining above brown wool.</p>
          <p>Eve frowned. Natalie was volatile and flew off the handle easily, but their father wasn't like that. The only thing that moved him deeply was a threat to his own comfort. Eve reflected, watching her young half-sister, that Charlotte had done her best to spoil her, but there was one quality in Natalie Charlotte hadn't been able to touch, and that was her generosity. The purse strings of the fortune left to Natalie by her mother were never drawn. She was always wide open, foolishly so sometimes, to an appeal for help. She had given a pension to Pussy, their old nurse, for life; she had sent the furnace man's son through college; she was god-mother to a half dozen local relief organizations, and Alicia was always running to her with "cases," not to speak of Gerald's demands or the demands of her long list of friends and acquaintances.</p>
          <p>Eve tossed her cigarette into the flames. If she was watching the others, Charlotte was watching her. Eve's spine stiffened. She turned toward the hearth, sipped a highball and answered Hugh's polite questions. The shop was doing very well, much better than she had expected.</p>
          <p>Her father didn't flinch. His small keen eyes were cold, but his manner remained bland, as if what she did were no longer of any importance. Yet he had objected furiously to her going into business, had wanted her to remain on and to marry, well, under the aegis of Natalie's wealth and position, which would have added to the Flavell prestige. The book shop he might have been able to swallow, books were cultural and not undignified, but when she had added stockings and gloves he had thrown up his hands: "A female haberdasher, after four years of college &mdash; my dear girl. What an achievement! You must be proud of yourself."</p>
          <p>That was on the day she had refused to live an hour longer in Natalie's house, on Natalie's money. She had been very young and very stupid and crude in the way she went about it, accusing the others by indirection &mdash; her father and Charlotte, her brother Gerald and Alicia &mdash; of doing just that. No wonder they had resented her attitude. They had said she was pigheaded and ungrateful and eaten up by jealousy. This last at least was untrue. She was very fond of her young half-sister, but Natalie's wealth, her friends, her amusements, pursuits, and outlook were not Eve's and never could be.</p>
          <p>She had made the break as complete as possible. It had been difficult at times but on the whole exhilarating. The only one she had had any real trouble with was Natalie. With a large income at her disposal she couldn't understand why Eve wouldn't use her charge accounts or have her apartment furnished, and at first, anyhow, she had been hurt and unhappy at the division between them. But if their daily association had been curtailed their affection for each other was as strong as ever.</p>
          <p>Eve looked at Natalie's bent head, pale against a fall of green brocade, where she stood at a desk writing a check for some charity or other for a stout woman in elegant beige and sables, and warmth stirred in her around a core of central deadness. She had been right. She had done the only thing there was to do.</p>
          <p>The room was beginning to empty. Departing guests kept coming up to say good-bye to Hugh and Charlotte. Eve smoked and waited, holding taut nerves in check. It wouldn't be long now. "How's the book coming, Father?" she asked during a lull.</p>
          <p>Hugh was writing a book on Economic Victorianism. He had been engaged on it for a long while. The first volume, published nine years earlier, had been well received. The notices, all good, were pasted neatly in a scrapbook that occupied a lectern of its own in his study.</p>
          <p>Her father nodded without removing the cigarette from his lips. His aloof gaze said, <em>Don't try to come over me with that, you haven't the slightest interest in my work, or in me. You never had.</em></p>
          <p>Eve flushed and persevered. "There must be a tremendous amount of research to do."</p>
          <p>"There is." He was, definitely, thinking of other things.</p>
          <p>The conversation withered. Charlotte made no effort to keep it alive. Her labors at the tea table over, she had taken up her knitting. Her silence was disagreeable, menacing. It gave her the air of a judge &mdash; which was what she always had been to Eve, condemning her unheard, in advance, of the gravest crimes. But when she got up and went to speak to someone, it was no relief. Eve had always hated to be alone with her father. She never knew what to say to him. Now, in his absorption in whatever engrossed his thoughts, he was doubly formidable. Fortunately Alicia dropped into Charlotte's vacant place. Hugh was fond of the daughter-in-law whose social background was excellent, who was decorative, whom he considered a good wife and mother and who knew how to flatter him. Talk flowed between them easily.</p>
          <p>"You're not looking too well, Dad." Alicia put her dark, madonna-smooth head on one side. "Your eyes, yes, I think it's your eyes &mdash; they have no light in them. Have you been doing what Doctor Hendricks ordered?"</p>
          <p>Hugh relaxed insensibly. "I can't be bothered with all that nonsense."</p>
          <p>"Oh, but you must. Exercise &mdash; have you been taking your walks?"</p>
          <p>"That I do do. Five times around the Square after breakfast, five times after dinner."</p>
          <p>"And something to eat before you to to bed?"</p>
          <p>"I generally have a banana and a glass of milk."</p>
          <p>"It's about the only fruit you care for."</p>
          <p>Alicia was in good form. Natalie threw Eve an amused glance over the shoulder of a man she was talking to and made a face, and they smiled imperceptibly at each other. Natalie had grown, Eve decided. She wasn't a child anymore. She was out of Charlotte's leading strings. Freedom, marriage, a new deal, were going to be splendid for her. She would lose her flashing restlessness and flower like a plant in the sun. Presently Charlotte came back. "How many for dinner?" she wanted to know, lighting a cigarette. Eve shook her head. "Not me, either," Alicia said. "I'd love it, but we're dining with the Beauferts. Gerald's calling for me at &mdash; There he is now."</p>
          <p>Eve thought, with an inner flicker of irony, I'm going to have a full house, and watched her brother advance toward the fire, tall and erect and graceful in a well-cut gray suit. Gerald was always impeccably turned out. His bills used to cause riots when he was at college. He was much too attractive for his own good, she thought. Things had always been made too easy for him. He had their father's face but their mother's eyes &mdash; gray, thick-lashed, appealing, smoky eyes. There were new sets of lines at the corners of them, little crow's-feet of strain. As Alicia had said, he was probably worried about business. He had an expensive establishment to keep up &mdash; but it was the way he wanted to live.</p>
          <p>Gerald greeted Hugh and Charlotte affectionately, pecked at Alicia's cheek, showed surprise at seeing Eve &mdash; and pleasure. "The return of the prodigal, a nice prodigal. That hat's good on you, my lass. What brings you to the old manse? Business folded?"</p>
          <p>It was her cue, Eve thought. But she wanted to wait for Natalie, who was saying good-bye to a man and a girl near the archway. "The shop? Thanks, no, it's flourishing, Gerald," Eve said aloud.</p>
          <p>Natalie joined them then, and Hugh and Gerald both got up. Her father hadn't risen for her, Eve reflected. He wouldn't. That was part of the unstudied discourtesy with which her had always treated her. Natalie did look tired. Her thin cheeks were pale and the dust of freckles across her nose stood out more prominently than ever.</p>
          <p>"Here." Gerald took her by the shoulders and pushed her into a chair. "You're all in, chicken."</p>
          <p>Natalie smiled at him. "I am, rather."</p>
          <p>"What you need is a drink," Gerald said. "I'm going to mix us all one. This is going to be good. I got it from a fellow who used to be at the old Hoffman House." He went to the 18th-century liquor cabinet against the wall and opened squat doors.</p>
          <p>Alicia peered at him through the low light. "How many have you had already?"</p>
          <p>Her tone was sharp. Charlotte looked at her and then, quickly, at Gerald. Hugh gazed at the fire, his mouth compressed. He was a practicing Aristotelian and believed in moderation in all things. Two cocktails, and only two, were permissible before dinner.</p>
          <p>"Drink deep or touch not the Pierian spring," Gerald said, turning around and grinning amiably. "Alicia's my pet prohibitionist, did you know?"</p>
          <p>It was family stuff, trivial, unimportant &mdash; or so Eve considered it at the time. Nevertheless she registered with a sudden sharp flash and a pang of apprehension that it was in Gerald and Alicia too, a brittle unease, as though they were deeply stirred about something but didn't want it to show, wanted it, very determinedly, not to.</p>
          <p>She gave herself a mental shake. She was probably imagining the whole business. She took the glass Gerald handed her. The stem was cool between her fingers and smooth and firm; you could hold on to it. Alicia and her father on the low armchair between the sofas, with Gerald on a hassock in front of her, his shoulders against her knees; beyond the warm circle of fire and lamplight the rest of the room was dim, shadowy and empty at last. <em>Now</em>, she thought, <em>now</em>, and leaned forward a little.</p>
          <p>"I've got news for you, Nat."</p>
          <p>In spite of herself her voice wasn't entirely level. Charlotte's knitting needles came to a halt; Alicia's cigarette paused in mid-air; her father adjusted his pince-nez. Gerald said lazily, "Ah-ha &mdash; I thought so when I saw you here. Out with it, my girl."</p>
          <p>Natalie was looking at her with all her eyes. "News, Eve? Good news?"</p>
          <p>Eve thought, with a bitter pang of self-reproach, <em>She's afraid. How terrible! I have hurt her in the past &mdash; but never again.</em> Aloud she said, "I hope you'll think it's good. Jim Holland and I are going to be married."</p>
          <p>It wasn't what her father or Alicia or Gerald had expected to hear. She didn't glance at Charlotte. Natalie jumped up and gave her a quick kiss. "Oh, Eve, I'm so glad," she cried. "This is wonderful. I do like Jim and he's been crazy about you for ages. When did you decide? When's it to be?"</p>
          <p>"Almost immediately," Eve answered. "Probably in a couple of days. We've gotten the license, taken our tests. You see, Jim's &mdash; "</p>
          <p>Her voice stopped. She sat very still. Blackness was swimming up around her. She had waited too long. The man who shouldn't have been there had entered the house unheard while she was talking.</p>
          <p>Bruce Cunningham was back from Washington. He stood on the top step looking toward the group around the fire, looking past Natalie, at Eve. The gold buttons on his uniform winked. Nothing else about him moved.</p>
          <p>Eve thought despairingly, <em>Why did he have to come now? Why couldn't he have stayed away until it was over and I was gone?</em> And then like a warning bell close in fog &mdash; <em>Charlotte</em>.</p>
          <p>Charlotte was beside her on the couch. The others hadn't seen Bruce yet, their backs were to the hall and to the archway leading into it, but Bruce was within Charlotte's field of vision.</p>
          <p>Eve tried to fight clear of destroying panic. They had noticed her pause. She must make the best of it. She raised her head, said in a clear light voice, "It's Lieutenant Cunningham, just in time to hear my news," and wondered, desperately, what was going to happen.</p>
        </ChBod>
      </section>
      <br />
      <hr />
      <br />
      <section style={{ width: '800px', border: '1px solid black', margin: '0 auto', padding: '1rem', display: 'none'}}>
        <ChNum>CHAPTER 2</ChNum>
        <ChTit>The Groundwork for Murder</ChTit>
        <ChBod>
          <p>Nothing happened, absolutely nothing. Eve had stumbled up a whole flight of steps that wasn’t there. Natalie got up and went toward Bruce, her face radiant — she hadn’t expected him for another twenty-four hours, and they kissed and the rest called greetings, and Bruce strolled to the hearth, an arm around Natalie’s shoulders. He felicitated Eve: “I hope you’ll be very happy, Miss Flavell. I have no doubt at all that Holland will. Lucky fellow.”</p>
          <p>His lean dark face, with which his light eyes were in such contrast, was quiet. His smile was pleasant, agreeable, not sardonic or bitter. He looked as he usually did when he wasn’t particularly interested, except that the line of his angled jaw was a ridge, which might have been an effect of light. The others added their good wishes to his. Charlotte’s eyes expressed a grudging approval. Hugh was openly pleased. He had known Jim for years, had tutored him for his entrance exams at Yale and evidently considered him an excellent husband for, if not a black sheep, at any rate one of a very dark shade of brown.</p>
          <p>Eve settled back in her corner, drank the cocktail Gerald had mixed, and listened to voices that were far away. She felt like a spent swimmer fighting tumultuous seas who suddenly finds himself floating in a land-locked lagoon without knowing or caring how he got there. Her work was done. It was all over. She was empty, drained, and in pain, yet content. She could go in peace.</p>
          <p>She was mistaken. Before she could begin her leave-taking, Jim Holland arrived in search of her and, a little later, Charlotte was summoned to the phone to answer a long-distance call.</p>
          <p class="flourish">**</p>
          <p>When Eve was interrogated afterward as to precisely what took place in the house on that bleak December afternoon, where people were at given intervals, what was said and done, it was hard to be exact. There was a good deal of confusion and stir and moving about. Jim had known the family since he was a boy and they were all fond of him and interested in his new job as production engineer at a factory in Bridgeport. He was very pleased about it himself.</p>
          <p>Talk, laughter, questions, a drink for Jim — perhaps five minutes after he got there, one of the maids came in and said that Charlotte was wanted on the telephone. It was while Charlotte was out of the room that Eve had her brief and dreadful encounter with Bruce. She made no mention of that to the police, until the time came when she didn’t have to, when it was too late, when they already knew.</p>
          <p>Then, at the moment, her blood ran cold at the chance he, took. The others were standing in a knot near the piano, at which Gerald was seated plucking idly at the keys; she had gone to get the purse she had left on a coffee table at the hearth. She was picking up her purse when Bruce spoke. His voice was almost at her ear. She hadn’t heard him follow her and her heart hammered, furiously.</p>
          <p>What he said, musingly, almost indifferently, was, “You couldn’t wait, could you, Eve? Perhaps it was asking too much. Are you in love with Holland? He’s too old for you — and too fat.”’</p>
          <p>Eve was indignant and angry and frightened and wildly amused. Jim wasn’t any older, in relation to her, than Bruce was to Natalie, or not much — and Jim wasn’t fat. He was a big man, naturally; it was simply that he couldn’t get enough exercise with his stiff knee, injured in a car crash when he was thirty. As for waiting — what good would it have done? Bruce was engaged to Natalie, had been engaged to her for more than a year, and she was passionately in love with him; you had only to see them together to realize that. There wasn’t the slightest chance of her terminating the engagement of her own accord — which was the only way it would matter.</p>
          <p>Bruce was mad to talk to her like this, here. She said in a voice as low as his own, “Don’t, Bruce. I’ve made up my mind and nothing can change it. I’m going to marry Jim. It isn’t any sacrifice. I’m very fond of him. Besides, we’ve had all this out before. We’re in perfect agreement on one thing: Natalie mustn’t be hurt. And Charlotte suspects.”</p>
          <p>“Charlotte — what does she suspect?”</p>
          <p>The need for reticence had vanished. “That you — that I — ”</p>
          <p>“How do you know?”</p>
          <p>“She came to see me at the shop the day before yesterday. She told me so.”</p>
          <p>“Then it was Charlotte who made you do this?”</p>
          <p>Her “No,” wasn’t emphatic enough. She added hurriedly, “I would have done it anyhow. Jim’s a swell guy.” She turned her head. No one was looking at them. The others were listening to Jim telling a story, gesticulating with his stick. He told a story well. His voice was big, sure. The boom of it was reassuring, like the rest of him. She glanced up sideways at Bruce and a wave of sickness went through her. His mouth was clamped tight, and his eyes were narrowed and intent and smolderingly bright on nothing. He was unhappy, tortured — and in a dangerous mood.</p>
          <p>She had seen him like that only once before, on the night he came to the shop to get some books for Natalie, and they found out suddenly and without words what had grown up between them, unbidden, almost unrecognized, until it was too late. There was nothing they could do about it. They both realized that, or seemed to. They, or she rather, for Bruce had been strangely silent, had stamped on the sudden and terrible knowledge, denying its existence, pretending it wasn’t there. A week later Bruce had thrown up his job and rejoined the Air Force.</p>
          <p>If only his injury hadn’t sent him home, if only they had met when he was free. Well, they hadn’t, and wishful thinking was stupid and purposeless and a waste of time. She had cut the knot of an impossible situation by engaging herself to Jim. Her announcement had effectually squashed Charlotte’s suspicion. It mustn’t be reawakened. Charlotte mustn’t find them together like this, apart from the others. She was at the telephone in the booth under the stairs but she would be back at any moment….</p>
          <p>Fear unlocked Eve’s weary paralysis. She tucked her purse under her arm, started pulling on her gloves. “I’m going now, Bruce,” she said quietly.</p>
          <p>He didn’t pay any attention. He remained as he was, staring down into the fire. “Charlotte,” he murmured thinly.</p>
          <p>He had never liked her aunt. Eve was afraid of his tone, his expression; she was more afraid of their isolation, of the shadowy corners, the unseen eyes that might be raking them speculatively.</p>
          <p>She said, “Don’t, Bruce. Think of Natalie. She’s the one we’ve got to think of,” and on that, without waiting for a response, she walked away, arranging her face, buttoning her glove, putting on a smile.</p>
          <p>Her back was to the fireplace and to the door beside it, a door leading into the dining-room beyond. The door had been open a few inches. Eve didn’t hear it close. Going into the dining-room a few minutes later, Gloria Fox, the parlor maid, found Charlotte Foy there, her face white, her hands gripping the back of a tall carved chair. The girl was frightened at her appearance but Miss Foy wouldn’t let her call anyone. She sent her upstairs for medicine, took it, and then said brusquely, “I’m all right now. Go back to your work.” When she returned to the living-room, Bruce Cunningham was gone. He had an engagement with a fellow officer. He left after arranging to have dinner somewhere with Natalie.</p>
          <p>Eve didn’t speak to him directly again. She said good-bye without looking at him. She didn’t need to look. The feel of him standing there beyond the archway, tall and straight in his uniform, was all through her. It was Thursday afternoon. She was going to be married to Jim Holland probably on Saturday. The anguish of farewell gripped her devastatingly. It wiped out everything else, so that for a while incidentals were blurred. She heard and saw, spoke and was spoken to, mechanically, in another world that had no real existence.</p>
          <p>Jim talked about Lordship Beach, said they thought of taking a house there. It was a swell place with a cliff coming up out of the sea. “It’s rather like Cornwall, isn’t it, Eve?” She said yes. Her father was pleased when he heard that she intended to give up the shop. “Now that’s what I call a good idea.” She said the wedding was going to be quiet but she and Jim wanted them all to come.</p>
          <p>“But of course, darling,” Alicia exclaimed. Natalie said wild horses wouldn’t keep her away. Charlotte said suddenly and harshly, “I can’t. I’ve got to go to Boston tomorrow.”</p>
          <p>She spoke in a loud voice as though she were making a declaration of faith before piled fagots. The others stared. In spite of her detachment, Eve felt a stiffening in them. It was mostly in her father but — did Gerald glance quickly at Alicia and did Alicia’s face tighten, so that for a moment she looked hag-ridden, ugly?</p>
          <p>Eve was puzzled. She could understand her father, but not Gerald or Alicia. Boston in that household meant the Coreys. Natalie’s mother, Virginia, had been a Corey. The old and extremely wealthy Boston family had strenuously objected to Virginia’s marriage to Hugh, who, at that time, even if he was a young and brilliant professor of economics was also penniless and a widower with two children to boot. After Virginia’s death, the Coreys had tried to obtain custody of Natalie in the courts. Hugh had very properly fought them and had won, but he had never forgiven his wife’s people and he hated the yearly trips Natalie made to her maternal aunt and cousins, trips on which Charlotte occasionally accompanied her.</p>
          <p>Jim was disappointed at Charlotte’s announcement. Unlike Bruce Cunningham, he was rather fond of her. He had known her when she was a good deal younger and she had been kind to him, as a boy. “Can’t you put off your trip?” he asked.</p>
          <p>She said no without explanation. Hugh made no attempt to hide his displeasure. The paper he was holding crackled sharply and he turned and walked away. He was in a towering rage; he did get into them sometimes, very suddenly. Ordinarily Charlotte was sensitive to his reactions, but not then. She repeated, “I’ve got to go.” Her face was gray and there were brownish pockets under her eyes.</p>
          <p>There was an odd little pause. Eve felt it again, more strongly, the presence of queer undercurrents in a family with which she had lost touch. What was worrying her aunt and Alicia and Gerald — and even Natalie? The whole thing was disturbing, disagreeable. She welcomed the interruption when it came.</p>
          <p>The phone in the hall rang. This time the call was for her. It was Clara Long, her assistant, talking from the shop. A prospective buyer had turned up, was there now — would Miss Flavell come?</p>
          <p>“At once,” Eve said. It altered her plans. She and lim had intended to go to Tony’s for rubbery spaghetti and red wine; she left the house almost immediately, alone.</p>
          <p>Natalie was cross. “Oh, Eve. I was making all sorts of plans,” she said. “I thought you and Jim would have joined Bruce and me somewhere later on this evening and we could have gone to El Morocco, they’ve got a marvelous new band, or to the Casablanca or to the Stork and talked.”</p>
          <p>“No, my pet,” Eve said firmly. Natalie loved to spend money on people and didn’t like to be thwarted, but Eve ignored her little pout of disappointment, kissed her and explained that it was impossible. She couldn’t afford to lose a chance of disposing of the business. “I’ll call you tomorrow.” She said good-bye to the others, and to Jim, “There’s no reason why you should hurry away. I’ll be busy for a while. Ring me in about an hour.”</p>
          <p>She didn’t encounter anyone in the hall. The door of the little writing-room under the stairs was shut. She opened the front door, closed it behind her, and was swallowed up instantly in fog. The fog was thick, impenetrable; it blanketed the entire Square. It was cold and very dark. The lamp above the door shed a feeble glow on the drenched bricks of the steps. Beyond them there was nothing but blackness and moisture and a bone-piercing chill.</p>
          <p>Eve was glad to be alone. She drank in solitude as a thirsty man drinks water. The Square was quiet, but then it always had been. Set down in the heart of New York, with the city sprawling away from it in every direction, it managed to hold itself apart and to produce a fictitious air of space and privacy and freedom from walls. Beyond it somewhere horns blasted feebly, and out on the river whistles blew. Eve descended the steps, one hand on the rail. She reached the pavement and turned left. Before she had gone more than a few feet she bumped into someone, violently.</p>
          <p>Arms steadied her. A man’s, voice said, “Oops — sorry. Are you all right?”</p>
          <p>Eve said, “Quite all right, thanks,” and proceeded more cautiously on her way.</p>
          <p>The park, locked and silent beyond its tall iron gates, was completely invisible. Her father wouldn’t take his walk that night. Or perhaps he would, with rubbers on and a coat of just the proper weight. He had always taken extraordinary care of himself. She could imagine him crossing the street and unlocking the gate and methodically pacing the paths through the thickets of the artificial wood behind the tall iron railings for the requisite length of time to the dot.</p>
          <p>She dallied with the thought of her father deliberately, putting aside thought of Bruce and Jim and herself. Natalie’s future was assured, and she had peace with honor; that was all that mattered. Meet other problems as they arose. As far as Jim went he was no romantic, love-sick boy. He was a man of thirty-seven and a realist. He wouldn’t demand the impossible. She would make him a good wife, could give him all he needed, a home, companionship, and intelligent interest in his work. Their minds were in tune, they were friends, laughed at the same things.  &hellip; </p>
          <p>She collided with a lamp post, blinked wetness that wasn’t fog angrily from her lashes, and went toward the pale glimmer of two enormous eyes that were the lamps of a cab in front of the apartment hotel on the corner. As she got in, slammed the door and gave the driver her address, a clock somewhere struck a quarter of six.</p>
          <p>There her actual knowledge of what further took place among the people in the red brick house with the blue shutters on that December day ended. Nevertheless she had in her possession then, without knowing it, the groundwork for murder. Certainly on that late afternoon and early evening, between half-past four when she entered the house and twenty minutes of six when she left it, the die was cast, irretrievably, into a cunning and malignant mold of planned destruction that very nearly, within a hair’s breadth, defied detection.</p>
          <p>It was almost the perfect crime. A tiny shred of green stuff invisible to the naked eye was what finally broke the case — that and a man’s shoes that didn’t fit and a speck of pink china dug from between the floor boards of a country house miles away. Christopher McKee, the head of the Manhattan Homicide Squad, exploring in the same sort of fog that filled the Square that night, had to learn where to look for these things and how to interpret them. Before that much had happened.</p>
        </ChBod>
      </section>
    </main>
  </div>
)